# Generated by Django 3.1.3 on 2021-01-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='jobselection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdes', models.CharField(max_length=1000)),
                ('relation3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.register')),
            ],
        ),
        migrations.CreateModel(
            name='jobseek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location2', models.CharField(max_length=250)),
                ('relation2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.register')),
            ],
        ),
        migrations.CreateModel(
            name='jobpro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location1', models.CharField(max_length=250)),
                ('jobdes', models.CharField(max_length=1000)),
                ('jobimg', models.FileField(upload_to='')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.register')),
            ],
        ),
    ]
